# Generated by Django 2.2.4 on 2019-08-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(max_length=255, verbose_name='Nome Responsavel')),
                ('cep', models.CharField(max_length=50, verbose_name='cep')),
                ('nome_ong', models.CharField(max_length=100, verbose_name='Nome Ong')),
                ('telefone', models.CharField(max_length=100, verbose_name='telefone')),
                ('horario', models.CharField(max_length=100, verbose_name='horario')),
                ('observacao', models.CharField(max_length=255, verbose_name='observacao')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
